name: hapet-site

services:
  softhub.docs:
    image: ${DOCKER_REGISTRY-}crackanddie/hapet
    build:
      context: .
      dockerfile: Dockerfile
      target: serve
    deploy:
      resources:
        limits:
          cpus: '0.50'
  softhub.docs.ru:
    image: ${DOCKER_REGISTRY-}crackanddie/hapet-ru
    build:
      context: .
      dockerfile: Dockerfile-ru
      target: serve
    deploy:
      resources:
        limits:
          cpus: '0.50'
  softhub.docs.zh:
    image: ${DOCKER_REGISTRY-}crackanddie/hapet-zh
    build:
      context: .
      dockerfile: Dockerfile-zh
      target: serve
    deploy:
      resources:
        limits:
          cpus: '0.50'
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/hapet_cert.crt:/etc/nginx/cert.crt
      - /etc/ssl/private/hapetlang.com.key:/etc/nginx/cert.rsa
    ports:
      - 5402:443
