version: '3.4'
name: softv-web

services:
  softhub.docs:
    image: ${DOCKER_REGISTRY-}crackanddie/softhubdocs
    build:
      context: .
      dockerfile: Dockerfile
      target: serve
    deploy:
      resources:
        limits:
          cpus: '0.50'
  softhub.docs.ru:
    image: ${DOCKER_REGISTRY-}crackanddie/softhubdocs-ru
    build:
      context: .
      dockerfile: Dockerfile-ru
      target: serve
    deploy:
      resources:
        limits:
          cpus: '0.50'
  softhub.docs.zh:
    image: ${DOCKER_REGISTRY-}crackanddie/softhubdocs-zh
    build:
      context: .
      dockerfile: Dockerfile-zh
      target: serve
    deploy:
      resources:
        limits:
          cpus: '0.50'
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/other/selfsigned.cert:/etc/nginx/cert.crt
      - ./certs/other/selfsigned.key:/etc/nginx/cert.rsa
    ports:
      - 5402:443
    depends_on:
      - softhub.api
  redis:
    image: ${DOCKER_REGISTRY-}crackanddie/redis
    container_name: redis_container_db
    build:
      context: .
      dockerfile: redis/Dockerfile
      target: final
    ports:
      - "6380:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true