version: '3.4'
name: softv-web

services:
  softhub.docs:
    image: ${DOCKER_REGISTRY-}crackanddie/softhubdocs
    build:
      context: .
      dockerfile: Dockerfile
      target: serve
    deploy:
      resources:
        limits:
          cpus: '0.50'
  softhub.docs.ru:
    image: ${DOCKER_REGISTRY-}crackanddie/softhubdocs-ru
    build:
      context: .
      dockerfile: Dockerfile-ru
      target: serve
    deploy:
      resources:
        limits:
          cpus: '0.50'
  softhub.docs.zh:
    image: ${DOCKER_REGISTRY-}crackanddie/softhubdocs-zh
    build:
      context: .
      dockerfile: Dockerfile-zh
      target: serve
    deploy:
      resources:
        limits:
          cpus: '0.50'
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/other/selfsigned.cert:/etc/nginx/cert.crt
      - ./certs/other/selfsigned.key:/etc/nginx/cert.rsa
    ports:
      - 5402:443
